using System.Text.Json;
using pfin.Model;
using pfin.Logging;

namespace pfin.Repository;

public class TransactionRepository : ITransactionRepository
{
    private IDebugLogger _logger = DebugLoggerFactory.CreateLogger(typeof(TransactionRepository));
    private static readonly JsonSerializerOptions _serializerOptions = new() { WriteIndented = true };
    // Path.Combine generated by ChatGPT so that the json file is accessible in the project root
    private static readonly string _filePath = Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "transactions.json");

    public List<Transaction> LoadAllTransactions()
    {
        _logger.Log($"Loading all transactions from {_filePath}");
        return JsonSerializer.Deserialize<List<Transaction>>(File.ReadAllText(_filePath)) ?? [];
    }

    public void SaveAllTransactions(List<Transaction> transactions)
    {
        _logger.Log($"Saving all transactions to {_filePath}");
        string json = JsonSerializer.Serialize<List<Transaction>>(transactions, _serializerOptions);
        File.WriteAllText(_filePath, json);
    }

}
